name: timer
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  injectable: ^0.4.0+1
  get_it: ^4.0.2
  auto_route: ^0.6.1
  cupertino_icons: ^0.1.3
  percent_indicator: ^2.1.5
  freezed_annotation: ^0.11.0
  intl: ^0.16.1
  flutter_bloc: ^6.0.1
  flutter_slidable: ^0.5.5
  dartz: ^0.9.2
  equatable: ^1.2.5
  moor: # use the latest version
  sqlite3_flutter_libs: # Also use the latest version.
  path_provider:
  path:

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
  freezed: ^0.11.2
  lint: ^1.2.0
  injectable_generator: ^0.4.1
  auto_route_generator: ^0.6.0
  moor_generator:
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/en.json
    - assets/i18n/fr.json
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Raleway/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Raleway/Raleway-Black.ttf
          weight: 900
